<?php

/**
 * Implements hook_apps_servers_info().
 *
 * Add the gateway_apps server
 */
function gateway_apps_apps_servers_info() {
  $profile = variable_get('install_profile', 'standard');
  $info =  drupal_parse_info_file(drupal_get_path('profile', $profile) . '/' . $profile . '.info');
  return array(
    'gateway' => array(
      'title' => 'Gateway',
      'description' => "Apps from Gateway",
      'manifest' => 'http://dev.web.gatewaypeople.com/app/query/Internal',
      'profile' => $profile,
      'profile_version' => isset($info['version']) ? $info['version'] : '7.x-1.x',
      'server_name' => $_SERVER['SERVER_NAME'],
      'server_ip' => $_SERVER['SERVER_ADDR'],
    ),
  );
}

/**
 * Implements hook_init().
 * 
 * Add a message if this is the vardot apps page.
 */
function gateway_apps_init() {
  if ($_GET['q'] == 'admin/apps/gateway') {
    apps_include('manifest'); 
    $server = apps_servers('gateway');
    // Create args array for substitutions
    $manifest = apps_manifest($server);
    if (isset($manifest['message']) && $manifest['message'] != '') {
      foreach($server as $key => $value) {
        $args['!' . $key] = $value;
      }
      drupal_set_message(format_string($manifest['message'], $args));
    }
  }
}
